# Generated by Django 2.1.2 on 2018-10-29 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieNiv1',
            fields=[
                ('id_categorie_niv_1', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='category name', max_length=40)),
            ],
            options={
                'verbose_name': 'rcategorie level 1',
            },
        ),
        migrations.CreateModel(
            name='CategorieNiv2',
            fields=[
                ('nom', models.CharField(default='category name', max_length=40)),
                ('id_categorie_niv_2', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_categorie_niv_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.CategorieNiv1')),
            ],
            options={
                'verbose_name': 'rcategorie level 2',
            },
        ),
        migrations.CreateModel(
            name='CategorieNiv3',
            fields=[
                ('nom', models.CharField(default='category name', max_length=40)),
                ('id_categorie_niv_3', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_categorie_niv_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='portfolio.CategorieNiv2')),
            ],
            options={
                'verbose_name': 'rcategorie level 3',
            },
        ),
    ]
