# Generated by Django 2.1.2 on 2018-11-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_categorieniv1_categorieniv2_categorieniv3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='city',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='country',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_date_upload',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='number_of_upload_this_day',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='orcid',
        ),
    ]
