# Generated by Django 2.1.2 on 2018-11-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181117_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieniv1',
            options={'verbose_name': 'categorie level 1'},
        ),
        migrations.AlterModelOptions(
            name='categorieniv2',
            options={'verbose_name': 'categorie level 2'},
        ),
        migrations.AlterModelOptions(
            name='categorieniv3',
            options={'verbose_name': 'categorie level 3'},
        ),
    ]
