# Generated by Django 2.1.2 on 2018-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20181117_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieniv1',
            name='id_categorie_niv_1',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorieniv2',
            name='id_categorie_niv_2',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorieniv3',
            name='id_categorie_niv_3',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
