# Generated by Django 2.1.2 on 2018-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20181117_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieniv1',
            name='nom_without_space',
            field=models.CharField(default='category name', max_length=100),
        ),
        migrations.AddField(
            model_name='categorieniv2',
            name='nom_without_space',
            field=models.CharField(default='category name', max_length=100),
        ),
        migrations.AddField(
            model_name='categorieniv3',
            name='nom_without_space',
            field=models.CharField(default='category name', max_length=100),
        ),
    ]
