# Generated by Django 2.1.2 on 2018-11-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20181117_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorieniv1',
            name='nom_without_space',
        ),
        migrations.RemoveField(
            model_name='categorieniv2',
            name='nom_without_space',
        ),
        migrations.RemoveField(
            model_name='categorieniv3',
            name='nom_without_space',
        ),
    ]
