# Generated by Django 2.1.2 on 2018-11-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20181117_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='default title', max_length=300)),
                ('resume', models.CharField(max_length=300, null=True)),
                ('content', models.TextField(default='lorem ipsum')),
                ('CategorieNiv1', models.ForeignKey(on_delete=None, to='portfolio.CategorieNiv1')),
                ('CategorieNiv2', models.ForeignKey(on_delete=None, to='portfolio.CategorieNiv2')),
                ('CategorieNiv3', models.ForeignKey(on_delete=None, to='portfolio.CategorieNiv3')),
            ],
        ),
    ]
