# Generated by Django 2.1.7 on 2019-03-26 14:52

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(default=None, max_length=200)),
                ('titre', models.CharField(default=None, max_length=100)),
                ('content', markdownx.models.MarkdownxField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_projet/')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Personne')),
            ],
        ),
    ]
