# Generated by Django 2.1.7 on 2019-04-15 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_article/')),
                ('date', models.DateField(default=datetime.date.today)),
                ('publish', models.BooleanField(default=False)),
                ('titre', models.CharField(default=None, max_length=100)),
                ('resume', models.CharField(default=None, max_length=200)),
                ('content', markdownx.models.MarkdownxField()),
                ('categorie', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Personne')),
            ],
        ),
    ]
