# Generated by Django 2.1.7 on 2019-02-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_projet/')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.Personne')),
            ],
        ),
    ]
