# Generated by Django 2.1.7 on 2019-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='lien_pdf',
            field=models.FileField(blank=True, null=True, upload_to='article_pdf/'),
        ),
    ]
