# Generated by Django 2.1.7 on 2019-04-02 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
