# Generated by Django 2.1.7 on 2019-04-18 07:37

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190416_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
