# Generated by Django 2.1.7 on 2019-03-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('article', '0003_auto_20190318_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie'),
        ),
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
