# Generated by Django 2.1.7 on 2019-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_auto_20190408_1005'),
        ('article', '0004_auto_20190403_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categorie_niv4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.CategorieNiv4'),
        ),
    ]
