# Generated by Django 2.1.7 on 2019-03-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieNiv1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieNiv2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(default=None, max_length=100)),
                ('cat_sup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categorie.CategorieNiv1')),
            ],
        ),
        migrations.CreateModel(
            name='CategorieNiv3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(default=None, max_length=100)),
                ('cat_sup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categorie.CategorieNiv2')),
            ],
        ),
    ]
