# Generated by Django 2.1.7 on 2019-04-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(default=None, max_length=100)),
                ('has_sub', models.BooleanField(default=False)),
                ('cat_sup', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie')),
            ],
        ),
    ]
