# Generated by Django 2.1.7 on 2019-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='niv_cat',
            field=models.IntegerField(choices=[(3, 3), (4, 4), (1, 1), (2, 2)], default=None, null=True),
        ),
    ]
