# Generated by Django 2.1.7 on 2019-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieniv1',
            name='has_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorieniv2',
            name='has_sub',
            field=models.BooleanField(default=False),
        ),
    ]
