# Generated by Django 2.1.7 on 2019-04-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_categorie_niv_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat_sup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie'),
        ),
    ]
