# Generated by Django 2.1.7 on 2019-04-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_auto_20190409_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='cat_sup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom_categorie',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
